server:
  port: 8081

spring:
  application:
    name: mapsphere

  datasource:
    url: jdbc:postgresql://localhost:5432/mapsphere
    username: postgres
    password: Admin@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
