spring:
  datasource:
    password: ${DB_PASSWORD:Admin@123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

mapsphere:
  seed:
    enabled: true

logging:
  level:
    com.mapsphere: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
